# Generated by Django 3.2.5 on 2021-07-13 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_details', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='mobile_no',
            new_name='mobileno',
        ),
    ]
