# Generated by Django 3.2.5 on 2021-08-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollnumber', models.CharField(max_length=100)),
                ('first', models.CharField(max_length=100)),
                ('last', models.CharField(max_length=100)),
                ('marks', models.CharField(max_length=100)),
            ],
        ),
    ]
